### ISSUE TITLE
Gui

### ISSUE THREAD

**Issue by Bashamega** [mshamir11/miniTwitter#6]
Hello:)
I Suggest adding some gui. it will be better than the terminal.

You can use something link [tkinter](https://docs.python.org/3/library/tkinter.html) I can work on it if you want

**Comment by mshamir11** [comment]
Hi Basha, Thank you for your suggestion. If you are interested go ahead.

**Comment by mshamir11** [comment]
Also check this project out : https://github.com/mshamir11/profSearch. There is scope for improvement in lots of area like refactoring  better UI, etc, etc. Feel free to open an issue if you want to suggest something. Many thanks again.

**Comment by Bashamega** [comment]
> Also check this project out : https://github.com/mshamir11/profSearch. There is scope for improvement in lots of area like refactoring better UI, etc, etc. Feel free to open an issue if you want to suggest something. Many thanks again.

thanks

**Comment by Bashamega** [comment]
> Hi Basha, Thank you for your suggestion. If you are interested go ahead.

I can't sorry, because I found that crypt is not for windows sorry
